#!/bin/sh


for dimension in 1 2 3 4;
do
    for numpoints in 16 32 64 128 256 512 1024;
    do
        ./randmst 0 $numpoints 40 $dimension;
    done
done


for dimension in 1 2 3 4;
do
    for numpoints in 2048 4096 8192 16384;
    do
        ./randmst 0 $numpoints 20 $dimension;
    done
done


for dimension in 1 2 3 4;
do
    for numpoints in 32768 65536 131072 262144;
    do
        ./randmst 0 $numpoints 5 $dimension;
    done
done

